export enum Exceptions {
  BAD_REQUEST_EXCEPTION = "BadRequestException",
  HTTP_EXCEPTION = "HttpException",
  UNAUTHORIZED_EXCEPTION = "UnauthorizedException",
  METHOD_NOT_ALLOWED_EXCEPTION = "MethodNotAllowedException",
  NOT_FOUND_EXCEPTION = "NotFoundException",
  FORBIDDEN_EXCEPTION = "ForbiddenException",
  NOT_ACCEPTABLE_EXCEPTION = "NotAcceptableException",
  REQUEST_TIMEOUT_EXCEPTION = "RequestTimeoutException",
  CONFLICT_EXCEPTION = "ConflictException",
  GONE_EXCEPTION = "GoneException",
  PAYLOAD_TOO_LARGE = "PayloadTooLargeException",
  UNSUPPORTED_MEDIA_TYPE_EXCEPTION = "UnsupportedMediaTypeException",
  UNPROCESSABLE_ENTITY_EXCEPTION = "UnprocessableEntityException",
  INTERNAL_SERVER_ERROR_EXCEPTION = "InternalServerErrorException",
  NOT_IMPLEMENTED_EXCEPTION = "NotImplementedException",
  HTTP_VERSION_SUPPORTED_EXCEPTION = "HttpVersionNotSupportedException",
  BAD_GATEWAY_EXCEPTION = "BadGatewayException",
  SERVICE_UNAVAILABLE_EXCEPTION = "ServiceUnavailableException",
  GETAWAY_TIMEOUT_EXCEPTION = "GatewayTimeoutException",
  PRECONDITION_FAILED_EXCEPTION = "PreconditionFailedException",
  MISDIRECTED_EXCEPTION = "MisdirectedException",
}
